source ~/.vim/general_settings.vimrc
source ~/.vim/plugins.vimrc
source ~/.vim/functions.vimrc
source ~/.vim/autocomplete_brackets.vimrc
source ~/.vim/plugin_settings.vimrc
if has("autocmd")
	  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
	      \| exe "normal! g'\"" | endif
endif


"  ---  FILE TYPE SETTINGS --- "
filetype plugin indent on

if has('autocmd')
	autocmd filetype python set expandtab
endif

" --- Color Scheme and Looks --- "
colorscheme molokai
set splitright

"let g:solarized_termcolors=256
"set background=dark

set laststatus=2 "Always Show Bottom Bar"
"let g:airline_powerline_fonts=1
let g:airline_detect_paste=1
let g:airline#extensions#tabline#enabled=1

"let &colorcolumn="80,".join(range(120,999),",")
let &colorcolumn="80,120"

set omnifunc=syntaxcomplete
let &statusline = '%{substitute(system("git status -s"), "\n", " ", "g")}'
